# Práctica Clase 3

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [3]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [4]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [5]:
#lista + 1

In [6]:
arreglo = arreglo + 1

In [7]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [8]:
#lista**2

In [9]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

3. Sumar todos los elementos

In [10]:
print(arreglo.sum())
#print(lista.sum())

36


In [11]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [12]:
arreglo.shape

(8,)

In [13]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [14]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [15]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [16]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [17]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [18]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [19]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [20]:
a3 = a1 * a2
a3.shape

(2, 4)

In [21]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [22]:
###############################################################################################################################################################
# random.random, METODO PARA CREAR MATRICES CON NUMEROS RANDOM
###############################################################################################################################################################

a = np.random.random((4,2,3)) * 100 + 100
a

array([[[178.68171137, 118.80317108, 139.23733539],
        [187.43929015, 158.03852837, 130.97341542]],

       [[101.20049603, 115.32273479, 172.37935853],
        [182.80321402, 194.91330296, 166.28471419]],

       [[104.82664329, 146.81954756, 180.92126076],
        [118.18457354, 159.1262241 , 118.170664  ]],

       [[105.68984275, 108.90511496, 124.73998362],
        [125.6421785 , 160.46514196, 175.8618253 ]]])

In [23]:
a = np.random.random((4,4))

In [24]:
a

array([[0.26088386, 0.72491209, 0.18583389, 0.50787597],
       [0.95685   , 0.57980063, 0.52241256, 0.29902966],
       [0.9886785 , 0.78458411, 0.17608292, 0.92609554],
       [0.6730017 , 0.16142165, 0.09611806, 0.95560677]])

In [25]:
###############################################################################################################################################################
# dtype; SIRVE PARA INDICAR DE QUE TIPO QUEREMOS LOS VALORES DENTRO DE LA MATRIZ, EN ESTE CASO ENTERO, PODRIA SER TAMBIEN dtype='float'
###############################################################################################################################################################

a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [26]:
a

array([[ 10, -56,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int8)

In [27]:
a.sum()

519

In [28]:
###############################################################################################################################################################
# .STD SIRVE PARA SACAR LA DESVIACION ESTANDAR DE LA MATRIZ
###############################################################################################################################################################

a.std()

23.924904214367643

In [29]:
###############################################################################################################################################################
# .SORT PERMITE ORDENAR LA MATRIZ
###############################################################################################################################################################
###############################################################################################################################################################
# AXIS = 1 ------------- ORDENA LA MATRIZ HORIZONTALMENTE
###############################################################################################################################################################

a.sort(axis=1)

In [30]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [31]:
###############################################################################################################################################################
# MIENTRAS QUE EL AXIS = 0 ------------------ ORDENA LA MATRIZ VERTICALMENTE
###############################################################################################################################################################

a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [32]:
###############################################################################################################################################################
# FILTRA LA MATRIZ EN ESTE CASO PRIMERO VERTICALMENTE, INCLUYENDO EL PRIMER NUMERO Y EXCLUYENDO EL SEGUNDO (1:3), MISMO CASO PARA (0,3)
###############################################################################################################################################################

a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [33]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [34]:
###############################################################################################################################################################
# TRANSFORMA LA MATRIZ EN UN ARRAY DE NUMPY
###############################################################################################################################################################

a = np.array([l])

In [35]:
###############################################################################################################################################################
# .SHAPE INDICA DIMENSIONES DE LA MATRIZ
###############################################################################################################################################################

a.shape

(1, 4, 6)

In [36]:
###############################################################################################################################################################
# REDIMENSIONA LA MATRIZ, TENER EN CUENTA QUE LA CANTIDAD DE VALORES DEL REDIMENSIONADO COINCIDA CON LA MATRIZ ORIGINAL, EN ESTE CASO CON UNA MATRIZ 
# DE 4X6 (24 ELEMENTOS) A UNA DE 2X12 (24 ELEMENTOS)
###############################################################################################################################################################

a.reshape(2,12)
type(a)

numpy.ndarray

In [37]:
###############################################################################################################################################################
# .MATRIX, ESTO SIRVE PARA CREAR MATRICES, A DIFERENCIA DE UN ARRAY CUANDO A ESTE A MODO DE EJEMPLO LO ELEVAS AL CUADRADO (A**2) TE ELEVA AL CUADRADO LA MATRIZ
# MIENTRAS QUE EN UN ARRAY TE ELEVA AL CUANDRADO CADA ELEMENTO DENTRO DE LA MATRIZ
###############################################################################################################################################################

a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 
type(a)

[[1 2 3 4 5 6]]


numpy.matrix

In [38]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [39]:
###############################################################################################################################################################
# COMO DIJIMOS ANTES, CON UN ARRAY NO PODEMOS MULTIPLICAR ENTRE MATRICES, LO QUE HARIA ES MULTIPLICAR ELEMENTO A LEMENTO
###############################################################################################################################################################
c = a * b 
print(c) 

[[91]]


In [40]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
