In [21]:
###Import numpy as np and print the version number
 
import numpy as np

print(np.version.version)

print(np.__version__)

1.22.4
1.22.4


In [22]:
#Create a 1D array of numbers from 0 to 9

array1d = np.arange(10)  ############## arange crea el vector con la cantidad de num dada  

array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Create a 3×3 numpy array of all True’s


mat = np.arange(9).reshape(3,3)
print(mat < 10)

print("*"*100)

mat1= np.full((3,3), True , dtype=bool)   ######## full() function is used to return a new array of a given shape and data type filled with fill_value
print(mat1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
****************************************************************************************************
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [24]:
### Extract all odd numbers from arr


arr = np.arange(10)

condition = (arr % 2 == 1)

np.extract(condition,arr)

########### creo condicional y uso el method extract



array([1, 3, 5, 7, 9])

In [25]:
#Replace all odd numbers in arr with -1

arr1= np.arange(10)
arr1[condition == True] = -1   ###### no es necesario usar la condición, poniendo arr1[arr % ==1] = -1 , es suficiente
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
#Replace all odd numbers in arr with -1 without changing arr

arr2= np.arange(10)
out = np.where (arr % 2 == 1, -1, arr)  #The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
print (arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
#Convert a 1D array to a 2D array with 2 rows
arr3= np.arange(10).reshape(2,5)

arr3



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:

#Stack arrays a and b vertically



a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)    ###### PONER -1 hacer dedicir automaticamente la matriz posible

np.concatenate([a,b], axis=0)  #Method 1

#np.vstack([a,b]) #Method 2

#np.r_[a,b]  #Method 3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
#Stack the arrays a and b horizontally.

np.hstack((a,b))

#Method 2 :  np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [34]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.


a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
# Get the common items between a and b


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [43]:
#From array a remove all items present in array b

a = np.array([1,2,3,111,4,5])
b = np.array([11,1,2,3,45,6,7,8,9])    #Find the set difference of two arrays. Return the unique values in ar1 that are not in ar2

np.setdiff1d(a,b)

array([  4,   5, 111])

In [44]:
#Get the positions where elements of a and b match


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where (a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [47]:
#  Get all items between 5 and 10 from a

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [50]:
#Convert the function maxx that works on two scalars, to work on two arrays.


def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])